version: '3.5'
services:
  web:
    image: ${IMG_NAME}
    container_name: lotso_airdrop_server
    restart: always
    ports:
      - "8080:1423"
    depends_on:
      - mysql
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_DB: ${MYSQL_DB}
      API_URL: ${API_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CHAIN_ID: ${CHAIN_ID}
      CUTOFF_BLOCK: ${CUTOFF_BLOCK}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      DEBUG: ${DEBUG}
      TZ: ${TZ}
      API_MODE: ${API_MODE}
      DECIMALS: ${DECIMALS}
      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
      PAIR_ADDRESS: ${PAIR_ADDRESS}
      BUYER_REWARD_LIMIT: ${BUYER_REWARD_LIMIT}
      NOT_BUYER_REWARD_LIMIT: ${NOT_BUYER_REWARD_LIMIT}

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: '%'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 50M

volumes:
  mysql-data:
