version: '3.5'
services:
  web:
    image: ${IMG_NAME}
    container_name: lotso_airdrop_server
    restart: always
    ports:
      - "${SERVER_PORT:-8080}:1423"
    volumes:
      - /etc/letsencrypt/live/btiplatform.com/privkey.pem:/privkey.pem
      - /etc/letsencrypt/live/btiplatform.com/fullchain.pem:/fullchain.pem
    # depends_on:
    #   - mysql
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_DB: ${MYSQL_DB}
      API_URL: ${API_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CHAIN_ID: ${CHAIN_ID}
      CUTOFF_BLOCK: ${CUTOFF_BLOCK}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      DEBUG: ${DEBUG}
      TZ: ${TZ}
      API_MODE: ${API_MODE}
      DECIMALS: ${DECIMALS}
      PAIR_ADDRESS: ${PAIR_ADDRESS}
      BUYER_REWARD_LIMIT: ${BUYER_REWARD_LIMIT}
      NOT_BUYER_REWARD_LIMIT: ${NOT_BUYER_REWARD_LIMIT}
      SSL_CERT: /fullchain.pem
      SSL_KEY: /privkey.pem
    networks:
      - ${NETWORK_NAME:-lotso-main-network}

#   mysql:
#     image: mysql:8.0.27
#     container_name: mysql
#     restart: always
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_USER: root
#       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
#       MYSQL_DATABASE: ${DB_NAME}
#       TZ: Asia/Shanghai
#       MYSQL_ROOT_HOST: '%'

# volumes:
#   mysql-data:

networks:
  ${NETWORK_NAME:-lotso-main-network}:
    external: true